# Generated by Django 4.2.6 on 2023-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=100)),
                ("prep_time", models.CharField(blank=True, max_length=100)),
                ("cook_time", models.CharField(blank=True, max_length=100)),
                ("total_time", models.CharField(blank=True, max_length=100)),
                ("servings", models.CharField(blank=True, max_length=100)),
                ("yields", models.CharField(blank=True, max_length=100)),
                ("ingredients", models.CharField(blank=True, max_length=100)),
                ("directions", models.CharField(blank=True, max_length=100)),
                ("rating", models.FloatField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=100)),
                ("cuisine_path", models.CharField(blank=True, max_length=100)),
                ("nutrition", models.CharField(blank=True, max_length=100)),
                ("timing", models.CharField(blank=True, max_length=100)),
                ("img_src", models.URLField(blank=True, max_length=1000)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
