# Generated by Django 4.2.6 on 2023-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="directions",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
