# Generated by Django 4.2.6 on 2023-10-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipes_directions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="directions",
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="ingredients",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="rating",
            field=models.FloatField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="recipe_name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
