# Generated by Django 4.2.6 on 2023-10-25 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipes_directions_alter_recipes_ingredients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="modified_date",
        ),
    ]
