# Generated by Django 4.2.6 on 2023-10-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_recipes_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="nutrition",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
