# Generated by Django 4.2.6 on 2023-10-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_recipes_cook_time_alter_recipes_prep_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="cook_time",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="prep_time",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="servings",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="timing",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="total_time",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
