# Generated by Django 4.2.6 on 2023-11-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("recipes", "0007_alter_recipes_cook_time_alter_recipes_prep_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
            preserve_default=False,
        ),
    ]
