# Generated by Django 4.2.6 on 2023-11-09 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_recipes_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipes",
            options={"verbose_name": "recipe", "verbose_name_plural": "recipes"},
        ),
    ]
