# Generated by Django 4.2.6 on 2023-11-12 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0009_alter_recipes_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=1000)),
                ("prep_time", models.CharField(blank=True, max_length=200, null=True)),
                ("cook_time", models.CharField(blank=True, max_length=200, null=True)),
                ("total_time", models.CharField(blank=True, max_length=200, null=True)),
                ("servings", models.CharField(blank=True, max_length=300, null=True)),
                ("yields", models.CharField(blank=True, max_length=100, null=True)),
                ("ingredients", models.CharField(blank=True, max_length=1000)),
                ("directions", models.TextField(blank=True, max_length=10000)),
                ("rating", models.FloatField(blank=True, max_length=5)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("cuisine_path", models.CharField(blank=True, max_length=100)),
                ("nutrition", models.CharField(blank=True, max_length=1000)),
                ("timing", models.CharField(blank=True, max_length=1000, null=True)),
                ("img_src", models.ImageField(blank=True, upload_to="recipe_img")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user recipe",
                "verbose_name_plural": "user recipes",
            },
        ),
    ]
