# Generated by Django 4.2.6 on 2023-11-13 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_rename_userrecipes_userrecipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrecipe",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="userrecipe",
            name="url",
        ),
    ]
